####这个文件默认从classpath根目录或者当前目录加载
## 代码使用这个获取@Value(value = "${app.name}")
###注意后面的值有个空格
##可以对特定环境定义profile
app:
  name: acceptor

server:
  port: 8080

spring:
    dubbo:
         application:
            name: frontOrder
         registry:
            address: zookeeper://127.0.0.1:2181
         scan: com.business.acceptor
kafka:
   zookeeper.address: localhost:9092

